"""add price to test catalog

Revision ID: c2915026c9e4
Revises: 
Create Date: 2026-06-22 15:46:44.056485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2915026c9e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specimens')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    op.create_foreign_key(None, 'lab_results', 'users', ['verified_by'], ['id'])
    op.create_foreign_key(None, 'lab_results', 'users', ['entered_by'], ['id'])
    op.create_foreign_key(None, 'reports', 'users', ['approved_by'], ['id'])
    op.add_column(
        'test_catalog',
        sa.Column(
            'price',
            sa.Float(),
            nullable=True
        )
    )

    op.execute(
        "UPDATE test_catalog SET price = 0 WHERE price IS NULL"
    )

    op.alter_column(
        'test_catalog',
        'price',
        nullable=False
    )
    # op.alter_column('test_orders', 'visit_id',
            #    existing_type=sa.VARCHAR(),
            #    nullable=False)
    op.create_foreign_key(None, 'test_orders', 'users', ['physician_id'], ['id'])
    # op.alter_column('test_parameters', 'test_id',
            #    existing_type=sa.INTEGER(),
            #    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_parameters', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'test_orders', type_='foreignkey')
    op.alter_column('test_orders', 'visit_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('test_catalog', 'price')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('appointments_pkey'))
    )
    op.create_table('specimens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specimen_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('collected_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('barcode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('specimens_pkey'))
    )
    # ### end Alembic commands ###
